import { config } from "./config.js";

const ALERT_STATES = new Set([
  "EARLY_WATCH",
  "STRONG_WATCH",
  "BUY",
  "HOLD",
  "RECOVERY",
  "WARNING_PULLBACK",
  "EXIT_WARNING",
  "EXIT_NOW",
  "SKIP"
]);

function esc(v) {
  return String(v ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function money(v) {
  const n = Number(v);
  if (!Number.isFinite(n)) return "—";
  if (Math.abs(n) >= 1_000_000) return `$${(n/1_000_000).toFixed(2)}M`;
  if (Math.abs(n) >= 1_000) return `$${(n/1_000).toFixed(1)}K`;
  return `$${n.toFixed(2)}`;
}

function num(v, d = 2) {
  const n = Number(v);
  return Number.isFinite(n) ? n.toFixed(d) : "—";
}

function stateOf(result) {
  return String(
    result?.decision ||
    result?.signal ||
    result?.entryState ||
    ""
  ).trim().toUpperCase();
}

function previousScanState(history) {
  if (!Array.isArray(history) || history.length === 0) return "";
  const h = history[0] || {};
  const s = h.snapshot || {};
  return String(
    h.decision ||
    s.decision ||
    s.signal ||
    s.entryState ||
    ""
  ).trim().toUpperCase();
}

/*
 * V2.9:
 * Telegram suppression is based on the LAST SUCCESSFULLY SENT state,
 * not merely the previous scan state.
 *
 * This fixes the case where BUY was generated by a service/run that did
 * not have Telegram configured or Telegram failed. A later BUY scan must
 * still be delivered until BUY has actually been recorded as sent.
 */
function shouldAlert(result, history, sentState = null) {
  if (!config.telegramBotToken || !config.telegramChatId) {
    return { send: false, reason: "TELEGRAM_NOT_CONFIGURED" };
  }

  const current = stateOf(result);
  const previous = previousScanState(history);
  const lastSent = String(sentState || "").trim().toUpperCase();

  if (!ALERT_STATES.has(current)) {
    return {
      send: false,
      reason: "STATE_NOT_ALERTABLE",
      current,
      previous,
      lastSent
    };
  }

  // Only suppress after we know this exact state was successfully sent.
  if (current === lastSent) {
    return {
      send: false,
      reason: "STATE_ALREADY_DELIVERED",
      current,
      previous,
      lastSent
    };
  }

  // Avoid noisy first-scan SKIP alerts.
  if (!previous && current === "SKIP") {
    return {
      send: false,
      reason: "FIRST_SCAN_SKIP_SUPPRESSED",
      current,
      previous,
      lastSent
    };
  }

  return {
    send: true,
    reason: current === "BUY" ? "BUY_NOT_YET_DELIVERED" : "STATE_NOT_YET_DELIVERED",
    current,
    previous,
    lastSent
  };
}

function buildMessage(result, current, previous) {
  const symbol = esc(result.symbol || "?");
  const transition = previous
    ? `${esc(previous)} → <b>${esc(current)}</b>`
    : `<b>${esc(current)}</b>`;

  const risk = esc(result.risk || "—");
  const trajectory = esc(result.trajectory || "—");
  const signal = esc(result.signal || "—");
  const reason = esc(result.reason || "—");

  return [
    `🔎 <b>Crypto Hunter</b>`,
    ``,
    `<b>${symbol}</b>`,
    `State: ${transition}`,
    `Score: <b>${num(result.score)}</b>`,
    `Risk: ${risk}`,
    `Trajectory: ${trajectory}`,
    `Signal: ${signal}`,
    ``,
    `LP: ${money(result.pairLpUsd)}`,
    `MC: ${money(result.marketCapUsd)}`,
    `BR 5M: ${num(result.buyRatio5m)}x`,
    `BR 1H: ${num(result.buyRatio1h)}x`,
    `Live/All: ${result.tradablePairCount ?? "—"}/${result.pairCount ?? "—"}`,
    ``,
    `Reason: ${reason}`,
    ``,
    `<b>Source: Railway</b>`
  ].join("\n");
}

export async function sendStateChangeAlert(result, history = [], lastSentState = null) {
  const gate = shouldAlert(result, history, lastSentState);

  if (!gate.send) {
    return {
      sent: false,
      reason: gate.reason,
      current: gate.current || stateOf(result),
      previous: gate.previous || previousScanState(history)
    };
  }

  const text = buildMessage(result, gate.current, gate.previous);

  const res = await fetch(
    `https://api.telegram.org/bot${encodeURIComponent(config.telegramBotToken)}/sendMessage`,
    {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        chat_id: config.telegramChatId,
        text,
        parse_mode: "HTML",
        disable_web_page_preview: true
      })
    }
  );

  let body = null;
  try { body = await res.json(); } catch {}

  if (!res.ok || body?.ok === false) {
    const detail = body?.description || `HTTP ${res.status}`;
    throw new Error(`Telegram alert failed: ${detail}`);
  }

  return {
    sent: true,
    reason: "STATE_CHANGED",
    current: gate.current,
    previous: gate.previous,
    messageId: body?.result?.message_id ?? null,
    deliveredState: gate.current
  };
}
